version: '2'
services:
  cassandra-1:
    hostname: cassandra-1
    image: cassandra
    container_name: cassandra-1
    environment:
      CASSANDRA_BROADCAST_ADDRESS: "cassandra-1"
    ports:
    - 7000
    volumes:
    - 'cassandra1:/var/lib/cassandra'
    restart: always

volumes:
  cassandra1:
    driver: local
